Cpa jobs redesign
bcjobs/assets pull request #43
Opened 2018-01-08 06:41 UTC by reizelfranz

2018-01-08 18:11 UTC, johnnyoshika requested changes

2018-01-08 18:11 UTC, johnnyoshika commented on css/_common.less
> +.text-right { text-align: right; }
Are these necessary? They're already part of Bootstrap: https://getbootstrap.com/docs/3.3/css/#type-alignment

2018-01-08 18:11 UTC, johnnyoshika commented on css/_common.less
> +.pos-relative { position: relative; }
Is this necessary? We already have `flex-relative`: https://github.com/bcjobs/assets/blob/master/css/_common.less#L2000

2018-01-15 05:16 UTC, reizelfranz commented on css/_common.less
> +.pos-relative { position: relative; }
@johnnyoshika This has been removed

2018-01-23 22:39 UTC, merged